apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-rollout
  labels:
    app: web-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-deployment
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
        labels:
          app: web-deployment
    spec:
      containers:
        - name: pokedex
          image: victornastase/pokedex:v3.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
