apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-deploy
spec:
  selector:
    matchLabels:
      app: web-deployment
  replicas: 2
  template:
    metadata:
        labels:
          app: web-deployment
    spec:
      containers:
        - name: pokedex
          image: victornastase/pokedex:v3.2
          imagePullPolicy: Always
          ports:
          - containerPort: 80
