apiVersion: v1
kind: Pod
metadata:
  name: pokedex-pod
  labels:
    app: web
spec:
  containers:
    - name: pokedex
      image: victornastase/pokedex:v3.2
      ports:
        - containerPort: 8080
