apiVersion: v1
kind: Service
metadata:
  name: pokedex-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30011
    protocol: TCP
    name: pokedex-app-port
  selector:
    app: web-deployment
status:
  loadBalancer:
    ingress:
      - hostname: localhost
